### PR TITLE
ci(actions): create pull request to dragonfly-schema when honeybee-sc…

### PR DESCRIPTION
**Pull request by AntoineDao**
…hema is released

Rather than commit straight to master let's just create a PR to dragonfly-schema to check that new
honeybee-schema releases pass tests and then either merge or enact corrective actions.

### CODE REVIEW

**Comment by AntoineDao** [comment]
I have set the commit message to `fix(honeybee-schema): bump to $NEW_VERSION` which means that when it is merged a minor release of dragonfly will be made by default. The idea being that if anything needs to be changed in dragonfly schema then we can make other commits with indicators of what level of change has been implemented.

As per this will require a $GH_TOKEN to be saved in the repository secrets if this is not already the case.

One other thing. When bumping the version it is assumed that we will want to set the dependency to `honeybee-schema==x.y.z` instead of `honeybee-schema>=x.y.z`. I will let you decide which you think is more appropriate.

**Comment by mostaphaRoudsari** [comment]
Added GH_TOKEN secret to this repository.

**Comment by chriswmackey** [comment]
This will be a huge help, @AntoineDao . Thank you. Once you fix the other PR, we'll merge both of them in and test it all out.

**Comment by AntoineDao** [comment]
Merged https://github.com/ladybug-tools/dragonfly-schema/pull/15 so will merge this now.

**Pull request merged**
